// The roster of waifus + the shared emotion set.
// Images live at /waifu/<id>/<emotion>.png  (generated by scripts/gen-images.mjs)

export const EMOTIONS = [
  'neutral',
  'happy',
  'excited',
  'blush',
  'sad',
  'angry',
  'jealous',
  'surprised',
  'pleading',
  'smug',
  'sexy',
  'playful_kiss',
] as const;

export type Emotion = (typeof EMOTIONS)[number];

export type Waifu = {
  id: string;
  name: string;
  tagline: string;
  // A short description that drives BOTH the image style and the personality flavor.
  vibe: string;
  hair: string;
  accent: string; // UI accent color
};

export const WAIFUS: Waifu[] = [
  { id: 'yumi',    name: 'Yumi',    tagline: 'your clingy childhood friend',      vibe: 'soft pastel schoolgirl, oversized sweater, hopeless romantic, way too attached', hair: 'long pink twin-tails',          accent: '#ff7eb6' },
  { id: 'rei',     name: 'Rei',     tagline: 'the quiet one who notices everything', vibe: 'calm mysterious kuudere, lab coat over uniform, unsettlingly perceptive',         hair: 'short ice-blue bob',            accent: '#6ec1ff' },
  { id: 'akari',   name: 'Akari',   tagline: 'chaotic gremlin energy',            vibe: 'genki orange-haired tomboy, hoodie, fingerless gloves, gremlin smile',           hair: 'messy orange ponytail',         accent: '#ff9f43' },
  { id: 'momo',    name: 'Momo',    tagline: 'the gyaru who wants ALL the attention', vibe: 'tanned gyaru, heart hairpins, dramatic, flirts like a sport',                  hair: 'curly platinum-blonde',         accent: '#ffd93d' },
  { id: 'nova',    name: 'Nova',    tagline: 'cyberpunk netrunner girlfriend',    vibe: 'cyberpunk hacker, neon visor, choker, emotional-firewall-breaker vibe',          hair: 'neon-magenta undercut',         accent: '#ff4fd8' },
  { id: 'mei',     name: 'Mei',     tagline: 'catgirl maid, suspiciously curious', vibe: 'cat-ear maid, frilly apron, paw gloves, nosey nya',                              hair: 'chocolate brown with cat ears', accent: '#ff8fab' },
  { id: 'shizuku', name: 'Shizuku', tagline: 'goth-lolita princess with dangerous calm', vibe: 'gothic-lolita aristocrat, lace dress, parasol, elegant deadpan teasing, secretly soft', hair: 'long straight black hair',       accent: '#b38cff' },
  { id: 'hina',    name: 'Hina',    tagline: 'sleepy hoodie gremlin with dangerous honesty', vibe: 'sleepy cozy girl, oversized hoodie blanket, lavender hair, drowsy deadpan flirting', hair: 'fluffy lavender hair',            accent: '#c8a2ff' },
];

export const DEFAULT_WAIFU = WAIFUS[0].id;

export function getWaifu(id: string | null | undefined): Waifu {
  return WAIFUS.find((w) => w.id === id) || WAIFUS[0];
}

export function isEmotion(x: string): x is Emotion {
  return (EMOTIONS as readonly string[]).includes(x);
}
